# Absolute root path for MCTL data (ex: builds)
data-path: /home/minecraft/.mctl
# Nice level to use for compilation processes
build-niceness: 15
# The maximum number of package revisions to store before pruning
max-package-revisions: 5

# Map of servers for mctl to manage
servers:
  example:
    # Absolute root path for the server
    path: /home/minecraft/example
    # Command used to start the server in GNU screen.
    command: java -Xmx1G -server --add-modules=jdk.incubator.vector -jar purpur.jar
    # Timeout (in seconds) to wait before stopping the server. A server
    # message will be printed every 5 seconds before the server is
    # stopped. Disable this feature by setting the value to 0.
    stop-timeout: 60
    # List of packages used by the server
    packages:
      - Purpur
      - BlueMap
      - CoreProtect
      - DiscordSRV
      - EssentialsX
      - LuckPerms
      - LWCX
      - mcMMO
      - WorldBorder
      - WorldEdit
      - WorldGuard

# Map of packages referenced by the servers
packages:
  Purpur:
    # Repository for the package source
    repositories:
      Purpur:
        url: https://github.com/PurpurMC/Purpur.git
        type: git
        committish: ver/1.19.2

    # List of build commands to serially execute in order
    build-commands:
      - ./Purpur/gradlew --no-daemon -p Purpur clean applyPatches
      - ./Purpur/gradlew --no-daemon -p Purpur build createReobfPaperclipJar

    # List of artifacts to archive and install
    artifacts:
      # Key is the path relevative to the server root path. The key is
      # the pattern to match reletive to the build root path.
      purpur.jar: Purpur/build/libs/purpur\-paperclip\-[\.0-9]+\-R[\.0-9]+\-SNAPSHOT\-reobf\.jar

  BlueMap:
    repositories:
      BlueMap:
        url: https://github.com/BlueMap-Minecraft/BlueMap.git
        type: git
        committish: master

    build-commands:
      - ./BlueMap/gradlew --no-daemon -p BlueMap clean build

    artifacts:
      plugins/BlueMap.jar: BlueMap/build/release/BlueMap\-[\.0-9]+\-spigot\.jar

  CoreProtect:
    repositories:
      CoreProtect:
        url: https://github.com/PlayPro/CoreProtect.git
        type: git
        committish: master

    build-commands:
      - mvn -f CoreProtect -D project.branch=master clean package

    artifacts:
      plugins/CoreProtect.jar: CoreProtect/target/CoreProtect\-[\.0-9]+\.jar

  DiscordSRV:
    repositories:
      DiscordSRV:
        url: https://github.com/DiscordSRV/DiscordSRV.git
        type: git
        committish: master

    build-commands:
      - mvn -f DiscordSRV clean package

    artifacts:
      plugins/DiscordSRV.jar: DiscordSRV/target/DiscordSRV\-Build\-[\.0-9]+\-[a-z0-9]+\.jar

  EssentialsX:
    repositories:
      EssentialsX:
        url: https://github.com/EssentialsX/Essentials.git
        type: git
        committish: 2.x

    build-commands:
      - ./EssentialsX/gradlew --no-daemon -p EssentialsX clean build

    artifacts:
      plugins/EssentialsX.jar: EssentialsX/Essentials/build/libs/EssentialsX\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXAntiBuild.jar: EssentialsX/EssentialsAntiBuild/build/libs/EssentialsXAntiBuild\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXChat.jar: EssentialsX/EssentialsChat/build/libs/EssentialsXChat\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXDiscord.jar: EssentialsX/EssentialsDiscord/build/libs/EssentialsXDiscord\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXGeoIP.jar: EssentialsX/EssentialsGeoIP/build/libs/EssentialsXGeoIP\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXProtect.jar: EssentialsX/EssentialsProtect/build/libs/EssentialsXProtect\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXSpawn.jar: EssentialsX/EssentialsSpawn/build/libs/EssentialsXSpawn\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar
      plugins/EssentialsXXMPP.jar: EssentialsX/EssentialsXMPP/build/libs/EssentialsXXMPP\-[\.0-9]+\-dev\+[0-9]+\-[a-z0-9]+\.jar

  LuckPerms:
    repositories:
      LuckPerms:
        url: https://github.com/lucko/LuckPerms.git
        type: git
        committish: master

    build-commands:
      - ./LuckPerms/gradlew --no-daemon -p LuckPerms clean :bukkit:loader:buildNeeded

    artifacts:
      plugins/LuckPerms.jar: LuckPerms/bukkit/loader/build/libs/LuckPerms\-Bukkit\-[\.0-9]+\.jar

  LWCX:
    repositories:
      LWCX:
        url: https://github.com/pop4959/LWCX.git
        type: git
        committish: master

    build-commands:
      - mvn -f LWCX clean package

    artifacts:
      plugins/LWCX.jar: LWCX/target/LWCX\-[\.0-9]+\.jar

  mcMMO:
    repositories:
      mcMMO:
        url: https://github.com/mcMMO-Dev/mcMMO.git
        type: git
        committish: master

    build-commands:
      - mvn -f mcMMO clean package

    artifacts:
      plugins/mcMMO.jar: mcMMO/target/mcMMO\.jar

  WorldBorder:
    repositories:
      WorldBorder:
        url: https://github.com/Brettflan/WorldBorder.git
        type: git
        committish: master

    build-commands:
      - mvn -f WorldBorder clean package

    artifacts:
      plugins/WorldBorder.jar: WorldBorder/target/WorldBorder\.jar

  WorldEdit:
    repositories:
      WorldEdit:
        url: https://github.com/EngineHub/WorldEdit.git
        type: git
        committish: master

    build-commands:
      - ./WorldEdit/gradlew --no-daemon -p WorldEdit clean :worldedit-bukkit:buildNeeded

    artifacts:
      plugins/WorldEdit.jar: WorldEdit/worldedit\-bukkit/build/libs/worldedit\-bukkit\-[\.0-9]+\-SNAPSHOT\-dist\.jar

  WorldGuard:
    repositories:
      WorldGuard:
        url: https://github.com/EngineHub/WorldGuard.git
        type: git
        committish: master

    build-commands:
      - ./WorldGuard/gradlew --no-daemon -p WorldGuard clean :worldguard-bukkit:buildNeeded

    artifacts:
      plugins/WorldGuard.jar: WorldGuard/worldguard\-bukkit/build/libs/worldguard\-bukkit\-[\.0-9]+\-SNAPSHOT\-dist\.jar
