# Absolute root path for MCTL data (ex: builds)
data-path: /home/minecraft/.mctl
# Nice level to use for compilation processes
build-niceness: 15
# The maximum number of package revisions to store before pruning
max-package-revisions: 5

# Map of servers for mctl to manage
servers:
  example:
    # Absolute root path for the server
    path: /home/minecraft/example
    # Command used to start the server in GNU screen.
    command: java -Xmx1G -server -jar spigot.jar
    # Timeout (in seconds) to wait before stopping the server. A server
    # message will be printed every 5 seconds before the server is
    # stopped. Disable this feature by setting the value to 0.
    stop-timeout: 60
    # List of packages used by the server
    packages:
      - Spigot
      - DiscordSRV
      - dynmap
      - EssentialsX
      - LogBlock
      - LuckPerms
      - LWCX
      - mcMMO
      - WorldBorder
      - WorldEdit
      - WorldGuard

# Map of packages referenced by the servers
packages:
  Spigot:
    # List of files to fetch
    fetch-urls:
      BuildTools.jar: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

    # List of build commands to serially execute in order
    build-commands:
      - java -jar BuildTools.jar --rev 1.15.2

    # List of artifacts to archive and install
    artifacts:
      # Key is the path relevative to the server root path. The key is
      # the pattern to match reletive to the build root path.
      spigot.jar: spigot\-[\.0-9]+\.jar

  DiscordSRV:
    # Repository for the package source
    repositories:
      DiscordSRV:
        # URL of the repository
        url: https://github.com/DiscordSRV/DiscordSRV.git
        # Type of the repository (currently only git is supported)
        type: git
        # Branch, tag, or hash to work on within the repository
        committish: master

    build-commands:
      # https://github.com/DiscordSRV/DiscordSRV/issues/677
      - sed -i 's|http://jcenter.bintray.com|https://jcenter.bintray.com|' DiscordSRV/pom.xml
      - mvn -f DiscordSRV clean package

    artifacts:
      plugins/DiscordSRV.jar: DiscordSRV/target/DiscordSRV\-Build\-[\.0-9]+\.jar

  dynmap:
    repositories:
      dynmap:
        url: https://github.com/webbukkit/dynmap.git
        type: git
        committish: v3.0

    build-commands:
      - cd dynmap && ./gradlew clean :spigot:buildNeeded

    artifacts:
      plugins/dynmap.jar: dynmap/target/Dynmap\-[\.0-9]+\-SNAPSHOT\-spigot\.jar

  EssentialsX:
    repositories:
      EssentialsX:
        url: https://github.com/EssentialsX/Essentials.git
        type: git
        committish: 2.x

    fetch-urls:
      Spigot/BuildTools.jar: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

    build-commands:
      - cd Spigot && java -jar BuildTools.jar --rev 1.8
      - cd Spigot && java -jar BuildTools.jar --rev 1.8.3
      - mvn -f EssentialsX clean package

    artifacts:
      plugins/EssentialsX.jar: EssentialsX/Essentials/target/EssentialsX\-[\.0-9]+\.jar
      plugins/EssentialsXAntiBuild.jar: EssentialsX/EssentialsAntiBuild/target/EssentialsXAntiBuild\-[\.0-9]+\.jar
      plugins/EssentialsXChat.jar: EssentialsX/EssentialsChat/target/EssentialsXChat\-[\.0-9]+\.jar
      plugins/EssentialsXGeoIP.jar: EssentialsX/EssentialsGeoIP/target/EssentialsXGeoIP\-[\.0-9]+\.jar
      plugins/EssentialsXProtect.jar: EssentialsX/EssentialsProtect/target/EssentialsXProtect\-[\.0-9]+\.jar
      plugins/EssentialsXSpawn.jar: EssentialsX/EssentialsSpawn/target/EssentialsXSpawn\-[\.0-9]+\.jar
      plugins/EssentialsXXMPP.jar: EssentialsX/EssentialsXMPP/target/EssentialsXXMPP\-[\.0-9]+\.jar

  LogBlock:
    repositories:
      LogBlock:
        url: https://github.com/LogBlock/LogBlock.git
        type: git
        committish: master

    build-commands:
      - mvn -f LogBlock clean package

    artifacts:
      plugins/LogBlock.jar: LogBlock/target/LogBlock\.jar

  LWCX:
    repositories:
      LWCX:
        url: https://github.com/pop4959/LWCX.git
        type: git
        committish: master

    build-commands:
      - mvn -f LWCX clean package

    artifacts:
      plugins/LWCX.jar: LWCX/target/LWCX\-[\.0-9]+\.jar

  LuckPerms:
    repositories:
      LuckPerms:
        url: https://github.com/lucko/LuckPerms.git
        type: git
        committish: master

    build-commands:
      - cd LuckPerms && ./gradlew clean :bukkit:buildNeeded

    artifacts:
      plugins/LuckPerms.jar: LuckPerms/bukkit/build/libs/LuckPerms\-Bukkit\-[\.0-9]+\.jar

  mcMMO:
    repositories:
      mcMMO:
        url: https://github.com/mcMMO-Dev/mcMMO.git
        type: git
        committish: master

    build-commands:
      - mvn -f mcMMO clean package

    artifacts:
      plugins/mcMMO.jar: mcMMO/target/mcMMO\.jar


  WorldBorder:
    repositories:
      WorldBorder:
        url: https://github.com/Brettflan/WorldBorder.git
        type: git
        committish: master

    build-commands:
      - mvn -f WorldBorder clean package

    artifacts:
      plugins/WorldBorder.jar: WorldBorder/target/WorldBorder\.jar

  WorldEdit:
    repositories:
      WorldEdit:
        url: https://github.com/EngineHub/WorldEdit.git
        type: git
        committish: master

    build-commands:
      - cd WorldEdit && ./gradlew clean :worldedit-bukkit:buildNeeded

    artifacts:
      plugins/WorldEdit.jar: WorldEdit/worldedit\-bukkit/build/libs/worldedit\-bukkit\-[\.0-9]+\-SNAPSHOT\-dist.jar

  WorldGuard:
    repositories:
      WorldGuard:
        url: https://github.com/EngineHub/WorldGuard.git
        type: git
        committish: master

    build-commands:
      - cd WorldGuard && ./gradlew clean :worldguard-bukkit:buildNeeded

    artifacts:
      plugins/WorldGuard.jar: WorldGuard/worldguard\-bukkit/build/libs/worldguard\-bukkit\-[\.0-9]+\-SNAPSHOT\-dist.jar

